// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomerSwiper: typeof import('./../../src/components/customer-swiper/index.vue')['default']
    'IEp:userFilled': typeof import('~icons/ep/user-filled')['default']
    'IFe:appMenu': typeof import('~icons/fe/app-menu')['default']
    'IFlatColorIcons:barChart': typeof import('~icons/flat-color-icons/bar-chart')['default']
    'IIconPark:rankingList': typeof import('~icons/icon-park/ranking-list')['default']
    'IUiw:menu': typeof import('~icons/uiw/menu')['default']
    'IUiw:search': typeof import('~icons/uiw/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
