// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CustomerSwiper: typeof import('./../../src/components/customer-swiper/index.vue')['default']
    HomeSearch: typeof import('./../../src/components/home-search/index.vue')['default']
    HomeSideNav: typeof import('./../../src/components/home-side-nav/index.vue')['default']
    'IAntDesign:appstoreTwotone': typeof import('~icons/ant-design/appstore-twotone')['default']
    'IAntDesign:shoppingCartOutlined': typeof import('~icons/ant-design/shopping-cart-outlined')['default']
    'IEp:menu': typeof import('~icons/ep/menu')['default']
    'IEp:userFilled': typeof import('~icons/ep/user-filled')['default']
    'IFe:appMenu': typeof import('~icons/fe/app-menu')['default']
    'IFlatColorIcons:barChart': typeof import('~icons/flat-color-icons/bar-chart')['default']
    'IFlatColorIcons:bullish': typeof import('~icons/flat-color-icons/bullish')['default']
    'IFluent:alignLeft48Regular': typeof import('~icons/fluent/align-left48-regular')['default']
    'IFluent:alignRight48Regular': typeof import('~icons/fluent/align-right48-regular')['default']
    'IFluent:collections20Filled': typeof import('~icons/fluent/collections20-filled')['default']
    'IFluentMdl2:bookmarks': typeof import('~icons/fluent-mdl2/bookmarks')['default']
    'IFluentMdl2:bookmarksMirrored': typeof import('~icons/fluent-mdl2/bookmarks-mirrored')['default']
    'IGg:moreVerticalR': typeof import('~icons/gg/more-vertical-r')['default']
    'IIc:baselineMenu': typeof import('~icons/ic/baseline-menu')['default']
    'IIc:baselineRemoveRedEye': typeof import('~icons/ic/baseline-remove-red-eye')['default']
    'IIconPark:rankingList': typeof import('~icons/icon-park/ranking-list')['default']
    'IMajesticons:moreMenu': typeof import('~icons/majesticons/more-menu')['default']
    'IMdi:accountBoxMultiple': typeof import('~icons/mdi/account-box-multiple')['default']
    'IMdi:commentTextOutline': typeof import('~icons/mdi/comment-text-outline')['default']
    'IMdi:shoppingCartOutlined': typeof import('~icons/mdi/shopping-cart-outlined')['default']
    'IOpenmoji:fire': typeof import('~icons/openmoji/fire')['default']
    'IUiw:menu': typeof import('~icons/uiw/menu')['default']
    'IUiw:search': typeof import('~icons/uiw/search')['default']
    Link: typeof import('./../../src/components/link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleBox: typeof import('./../../src/components/ScaleBox.vue')['default']
    Serarch: typeof import('./../../src/components/serarch/index.vue')['default']
    SerarchNav: typeof import('./../../src/components/serarch-nav/index.vue')['default']
    ShCard: typeof import('./../../src/components/sh-card/index.vue')['default']
    SimpSwiper: typeof import('./../../src/components/simp-swiper/index.vue')['default']
    Skeleton: typeof import('./../../src/components/skeleton.vue')['default']
    Swiper: typeof import('./../../src/components/swiper/index.vue')['default']
  }
}
